# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Sensory and Evolutionary Ecology (SEE)
subtitle: "Thomas E. White"
email: thomas.white@sydney.edu.au
name: Thomas E. White
description: >
  Sensory and Evolutionary Ecology (SEE)
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://tomwhite.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Navigation bar
nav_order:
  - Research
  - Publications
  - People
  - Join!
  - Media
  - Tools
  - Values

# Social icons and sharing options
social:
  - name: GitHub
    icon: github
    username: thomased
    url: https://github.com/thomased
    desc: Fork me on GitHub
    share: false

  - name: Scholar
    icon: google
    username: Thomas E. White
    url: https://scholar.google.com.au/citations?user=IJk91k0AAAAJ&hl=en
    desc: Find me on Google Scholar
    share: false
    