# Blog settings
#permalink: /blog/:title

# My variables
name: Thomas White
description: Evolution | Ecology | Behaviour
google_verification: null

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"
